version: "3"

services:
  goodreads:
    build:
      context: ../.
    ports:
      - "8080:8080"
    networks:
      - goodreads
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - goodreads-mail-sender
  postgres:
    image: postgres
    networks:
      - goodreads
    env_file:
      - .env
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - goodreads
    ports:
      - '5672:5672'
  redis:
    image: redis
    networks:
      - goodreads
    ports:
      - '6379:6379'
  goodreads-mail-sender:
    image: goodreads-mail-sender
    networks:
      - goodreads
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - '8081:8081'

networks:
  goodreads:
    driver: bridge


