spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: goodreads
  messages:
    basename: i18n/messages
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true
  rabbitmq:
    host: goodreads
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false
  main:
    banner-mode: off

client:
  openlib:
    url: https://openlibrary.org/

logging:
  level:
    com.company.goodreadsapp: debug

jwt:
  secretKey: ${JWT_SECRET}
  issuer: ${ISSUER}
  token:
    access:
      expireInMinutes: 5
    refresh:
      expireInMinutes: 10

redis:
  url: ${REDIS_URL}